services:
  benchmark:
    build:
      context: .
      dockerfile: Dockerfile
    image: coding-agent-benchmark-cpp:latest
    container_name: agent_benchmark_cpp
    volumes:
      - ../..:/app
      # Пробрасываем базу promptfoo на хост, чтобы логи не сгорали при --rm
      - ./logs/promptfoo_data:/home/node/.promptfoo   # было /root/.promptfoo, но перешли на безопасного пользователя node (в частности требование запуска claude cli)
    working_dir: /app/benchmarks/cpp-gtest-fix
    env_file:
      - ../../.env        
    environment:
      - PROMPTFOO_DISABLE_TELEMETRY=true
      - PROMPTFOO_PYTHON=python3
    entrypoint: []
    # Идеология одной команды: авто-кэш (сохранение директории сборки, чтобы не пересобирать каждый раз заново) -> молниеносный сброс диффа -> запуск теста
    command: bash -c "./setup.sh && ( [ -d workspace/googletest ] && git -C workspace/googletest reset --hard HEAD && git -C workspace/googletest clean -fd -e build ) && promptfoo eval"